orbs:
  aws-ecr: circleci/aws-ecr@6.12.2
  aws-ecs: circleci/aws-ecs@1.3.0
version: 2.1

workflows:
  ci:
    jobs:
      - build-image:
          context: Production
  cd:
    jobs:
      - aws-ecr/build-and-push-image:
          context: Production
          create-repo: true
          repo: hayden-wade-api
          tag: latest
          filters:
            branches:
              only: master
      - aws-ecs/deploy-service-update:
            context: Production
            requires:
              - aws-ecr/build-and-push-image
            family: 'hayden-wade-api'
            cluster-name: 'default'
            container-image-name-updates: 'container=hayden-wade-api,tag=latest'
jobs:
  build-image:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.12
      - aws-ecr/build-image:
          repo: hayden-wade-api
          tag: latest