orbs:
  aws-ecr: circleci/aws-ecr@6.12.2
version: 2.1

workflows:
  ci:
    jobs:
      - build-image:
          context: Production
  cd:
    jobs:
      - aws-ecr/build-and-push-image:
          context: Production
          create-repo: true
          repo: hayden-wade-api
          tag: latest
          filters:
            branches:
              only: master
jobs:
  build-image:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - aws-ecr/build-image:
          repo: hayden-wade-api
          tag: latest